CREATE TABLE `player_decks` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`playerId` BIGINT(20) NOT NULL,
	`name` VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY (`id`),
  FOREIGN KEY (playerId) REFERENCES players(id)
);